export { decideVerdict, stricterVerdict, verdictAtLeast } from './policy.js'
export {
  inspectNpmPackage,
  parseNpmSpec,
  resolveNpmDependencyGraph,
  verifyIntegrity,
  verifyRegistrySignatures,
  type InspectNpmOptions,
  type IntegrityResult,
  type NpmDependencyGraphOptions,
  type ParsedNpmSpec,
} from './npm.js'
export { renderTextReport } from './render.js'
export { dependencyGraphDigest, findDependencyPaths, parseNpmLockGraph, parsePnpmLockGraph } from './graph.js'
export {
  REVERSE_DEPENDENCY_INDEX_SCHEMA,
  buildReverseDependencyIndex,
  findReverseDependencyEntry,
  findReverseDependencyImpacts,
  parseReverseDependencyIndex,
  parseReverseDependencyObservations,
  type ReverseDependencyEntry,
  type ReverseDependencyIndex,
  type ReverseDependencyIndexInputs,
  type ReverseDependencyImpact,
  type ReverseDependencyObservation,
  type ReverseDependencyPackageChange,
  type ReverseDependencyPath,
  type ReverseDependencyPlugin,
  type ReverseDependencyPluginObservation,
  type ReverseDependencyUse,
} from './dependency-index.js'
export { parseInstalledNodeModulesGraph } from './installed-graph.js'
export {
  discoverDshRuntimeHostNodeModulesDirectory,
  discoverDshRuntimeNodeModulesDirectory,
  discoverDshRuntimePackage,
  discoverDshRuntimePackageDirectory,
  discoverDshRuntimePackageFromNodeModulesDirectory,
} from './dsh-runtime.js'
export { OsvClient, packageKey, type OsvClientOptions } from './osv.js'
export {
  NpmReleaseClient,
  isTransientNpmReleaseFailure,
  type NpmReleaseCandidateStatus,
  type NpmReleaseClientOptions,
  type NpmReleaseObservation,
  type NpmReleaseQueryFailure,
  type NpmReleaseQueryResult,
} from './npm-release.js'
export { MAX_CANDIDATE_GRAPHS, NpmCandidateGraphClient, type NpmCandidateGraphClientOptions } from './npm-candidate.js'
export { GitHubReleaseClient, type GitHubReleaseClientOptions, type ReleaseNotes, type ReleaseNotesSource } from './github-release.js'
export { GitHubAdvisoryClient, type GitHubAdvisoryClientOptions } from './github-advisory.js'
export {
  CisaKevClient,
  EpssClient,
  THREAT_INTEL_REFERENCES,
  type CisaKevClientOptions,
  type EpssClientOptions,
  type ThreatIntelSource,
  type ThreatIntelSourceBinding,
} from './threat-intel.js'
export {
  emptyRadarState,
  pollRadar,
  type AdvisorySource,
  type AdvisorySourceBinding,
  type CandidateDependencySource,
  type RadarPollResult,
  type ReleaseSource,
} from './radar.js'
export { assessCompatibilityChange, assessCompatibilityChanges, type CompatibilityChangeInput } from './compatibility.js'
export {
  DSH_LOAD_MATRIX_SCHEMA,
  DSH_LOAD_PROBE_SCHEMA,
  inspectDshLoadArtifact,
  probeDshLoad,
  probeDshLoadMatrix,
  renderDshLoadProbe,
  renderDshLoadMatrix,
  summarizeDshLoadResults,
  type DshLoadProbeArtifact,
  type DshLoadMatrixOptions,
  type DshLoadMatrixReport,
  type DshLoadMatrixSummary,
  type DshLoadProbeOptions,
  type DshLoadProbeReport,
  type DshLoadProbeResult,
  type DshProbeStage,
} from './dsh-probe.js'
export {
  DSH_INSTALL_OBSERVATION_SCHEMA,
  observeDshPluginInstall,
  parseDshInstallTrace,
  renderDshInstallObservation,
  type DshInstallObservationOptions,
  type DshInstallProfileLockfileEvidence,
  type DshInstallPluginPeerContracts,
  type DshInstallPeerContractIssue,
  type DshInstallPeerContractRelation,
  type DshInstallPeerStaticUsage,
  type DshInstallRuntimeGraphEvidence,
  type DshInstallObservationReport,
  type DshInstallObservationResult,
  type InstallFilesystemDiff,
  type InstallObservationCommand,
  type InstallObservationCommandResult,
  type InstallObservationIsolationProvider,
  type InstallObservationPhase,
  type InstallObservationRunner,
  type InstallObservationStage,
  type InstallTraceFileWrite,
  type InstallTraceNetwork,
  type InstallTraceObservation,
  type InstallTraceProcess,
} from './dsh-install-observation.js'
export {
  DSH_SURFACE_OBSERVATION_SCHEMA,
  dshSurfaceProfileStrategy,
  evaluateDshTuiEvidence,
  evaluateDshWebEvidence,
  observeDshPluginSurface,
  renderDshSurfaceObservation,
  type DshExecutionPlane,
  type DshSurfaceEvaluation,
  type DshSurfaceFailedStage,
  type DshSurfaceIsolationProvider,
  type DshSurfaceObservationOptions,
  type DshSurfaceObservationReport,
  type DshSurfaceObservationResult,
  type DshSurfaceStage,
  type DshTuiEvaluationInput,
  type DshTuiSurfaceEvidence,
  type DshWebEvaluationInput,
  type DshWebSurfaceEvidence,
} from './dsh-surface-observation.js'
export {
  DSH_SURFACE_AGENT_PLANS_SCHEMA,
  createDshSurfaceAgentInputFingerprint,
  emptyDshSurfaceAgentPlans,
  parseDshSurfaceAgentDecision,
  parseDshSurfaceAgentPlans,
  renderDshSurfaceAgentPrompt,
  type DshSurfaceAgentAction,
  type DshSurfaceAgentCandidate,
  type DshSurfaceAgentClassification,
  type DshSurfaceAgentDecision,
  type DshSurfaceAgentPlanEntry,
  type DshSurfaceAgentPlans,
} from './dsh-surface-agent-plan.js'
export {
  DSH_SURFACE_IR_SCHEMA,
  DSH_SURFACE_LEDGER_SCHEMA,
  DSH_SURFACE_TARGETS_SCHEMA,
  buildDshSurfaceIR,
  buildDshSurfacePlan,
  createDshSurfaceSourceFingerprint,
  emptyDshSurfaceLedger,
  hasDshWebClientCoverageGap,
  isDshWebClientOnlyCoverageGap,
  mergeDshSurfaceLedger,
  parseDshSurfaceLedger,
  parseDshSurfaceTargets,
  renderDshSurfaceLedgerMerge,
  type DshSurfaceExpectedCase,
  type DshSurfaceIR,
  type DshSurfaceLedger,
  type DshSurfaceLedgerEntry,
  type DshSurfaceLedgerMerge,
  type DshSurfacePlan,
  type DshSurfaceTarget,
  type DshSurfaceTargets,
  type DshSurfaceTransition,
} from './dsh-surface.js'
export {
  DSH_COMPATIBILITY_LEDGER_SCHEMA,
  createDshCompatibilityContractFingerprint,
  createDshCompatibilityStaticFingerprint,
  dshCompatibilityCaseId,
  emptyDshCompatibilityLedger,
  mergeDshCompatibilityLedger,
  parseDshCompatibilityLedger,
  renderDshCompatibilityLedgerMerge,
  type DshCompatibilityExpectedCase,
  type DshCompatibilityLedger,
  type DshCompatibilityLedgerEntry,
  type DshCompatibilityLedgerMerge,
  type DshCompatibilityPeerContractIssue,
  type DshCompatibilityPeerContractRelation,
  type DshCompatibilityPluginPeerContracts,
  type DshCompatibilityProfileLockfile,
  type DshCompatibilityRuntimeGraph,
  type DshCompatibilityTransition,
  type DshCompatibilityTransitionStatus,
} from './dsh-compatibility-ledger.js'
export {
  DSH_COMPATIBILITY_ISSUE_LABELS,
  buildDshCompatibilityIssuePlan,
  dshCompatibilityIssueCaseId,
  dshCompatibilityIssueMarker,
  renderDshCompatibilityIssue,
  renderDshCompatibilityReviewReclassification,
  renderDshCompatibilityResolution,
  type DshCompatibilityExistingIssue,
  type DshCompatibilityIssueAction,
  type DshCompatibilityIssuePlan,
} from './dsh-compatibility-issues.js'
export {
  DSH_COMPATIBILITY_IR_SCHEMA,
  DSH_COMPATIBILITY_REVERSE_INDEX_SCHEMA,
  buildDshCompatibilityIR,
  buildDshCompatibilityReverseIndex,
  parseDshCompatibilityIR,
  parseDshCompatibilityReverseIndex,
  type DshCompatibilityIR,
  type DshCompatibilityIrCell,
  type DshCompatibilityIrPlugin,
  type DshCompatibilityIrRelation,
  type DshCompatibilityIrRuntime,
  type DshCompatibilityPeerStatus,
  type DshCompatibilityReverseDependency,
  type DshCompatibilityReverseImpact,
  type DshCompatibilityReverseIndex,
} from './dsh-compatibility-ir.js'
export {
  DSH_INSTALL_TARGETS_SCHEMA,
  buildDshInstallPlan,
  parseDshInstallTargets,
  type DshInstallPlan,
  type DshInstallRuntimeProfile,
  type DshInstallTarget,
  type DshInstallTargets,
} from './dsh-install-plan.js'
export {
  AWESOME_DSH_COHORT_SCHEMA,
  DSH_DIRECTORY_COMPATIBILITY_FEED_SCHEMA,
  buildDshDirectoryCompatibilityFeed,
  parseAwesomeDshCohort,
  renderDshDirectoryCompatibilityFeed,
  type AwesomeDshCohort,
  type AwesomeDshCohortPlugin,
  type DshDirectoryCompatibilityEntry,
  type DshDirectoryCompatibilityFeed,
  type DshDirectoryEvidenceCell,
  type DshDirectoryEvidenceStatus,
} from './dsh-directory-feed.js'
export {
  DSH_PLUGIN_REVIEW_SCHEMA,
  renderDshPluginReview,
  reviewDshPlugin,
  type DshPluginReviewArtifact,
  type DshPluginReviewOptions,
  type DshPluginReviewReport,
  type DshPluginReviewStatus,
} from './dsh-review.js'
export {
  COMPATIBILITY_BENCHMARK_SCHEMA,
  renderCompatibilityBenchmark,
  runCompatibilityBenchmark,
  type CompatibilityBenchmarkCaseResult,
  type CompatibilityBenchmarkReport,
} from './compatibility-benchmark.js'
export { createAnalysisTask, renderAgentAnalysisGroupPrompt, renderAgentAnalysisPrompt, renderDshAnalysisPrompt } from './dsh-analysis.js'
export {
  DSH_PROFILE_CHECK_SCHEMA,
  checkDshProfile,
  renderDshProfileCheck,
  renderDshProfileCheckSummary,
  type DshPatchLoaderEntry,
  type DshProfileBundleObservation,
  type DshProfileCheckReport,
  type DshProfileCheckOptions,
  type DshProfileCheckStatus,
  type DshProfileFinding,
  type DshProfileFindingCode,
  type DshProfileFindingSeverity,
  type DshReleaseAgePolicy,
} from './dsh-profile-check.js'
export { DEMO_SCHEMA, createDemoEvent, createDemoReport, renderDemo, type DemoReport } from './demo.js'
export {
  DSH_CASE_SCHEMA,
  createDshCaseReport,
  renderDshCase,
  type DshCaseCheck,
  type DshCaseFinding,
  type DshCaseReport,
} from './dsh-case.js'
export {
  QUICKSTART_SCHEMA,
  createQuickstartReport,
  renderQuickstartReport,
  type QuickstartEffect,
  type QuickstartMode,
  type QuickstartOptions,
  type QuickstartReport,
  type QuickstartStep,
} from './quickstart.js'
export {
  extractAnalysisTaskIds,
  parseAgentAnalysisResult,
  renderAnalysisTaskMarker,
} from './dsh-analysis-result.js'
export { parsePackageManifestSnapshot, parseRadarConfig } from './inventory.js'
export {
  UPSTREAM_DOWNSTREAM_IR_SCHEMA,
  buildUpstreamDownstreamIR,
  parseUpstreamDownstreamIR,
  type AlignmentCheck,
  type AlignmentCheckCode,
  type AlignmentCoordinate,
  type AlignmentGraphStatus,
  type AlignmentStatus,
  type UpstreamDownstreamAlignmentInput,
  type UpstreamDownstreamIR,
} from './upstream-alignment.js'
export {
  OBSERVER_REPORT_SCHEMA,
  OBSERVER_TARGETS_SCHEMA,
  OBSERVATION_STATE_SCHEMA,
  UPSTREAM_CHANGE_TASK_SCHEMA,
  UpstreamObserverClient,
  createUpstreamChangeTask,
  emptyObservationState,
  loadObservationState,
  parseObservationState,
  parseObserverConfig,
  parseObserverConfigText,
  renderObserverReport,
  renderUpstreamChangeAgentPrompt,
  runDshAgentCommand,
  runOpenAiCompatibleAgent,
  runObserver,
  saveObservationState,
  type ObserverAgentCommandOptions,
  type OpenAiCompatibleAgentOptions,
  type ObserverAgentInvocation,
  type ObserverChange,
  type ObserverConfig,
  type ObserverEcosystem,
  type ObserverGraphChange,
  type ObserverLockfileType,
  type ObserverManifestChange,
  type ObserverPackageObservation,
  type ObserverReport,
  type ObserverSnapshot,
  type ObserverSnapshotSummary,
  type ObserverSource,
  type ObserverSourceChange,
  type ObserverSourceObservation,
  type ObserverTarget,
  type ObservationState,
  type RunObserverOptions,
  type UpstreamChangeTask,
  type UpstreamObserverClientOptions,
} from './upstream-observer.js'
export {
  countPolicyHeldAnalysisTasks,
  createNotificationPolicyMap,
  decideProjectRadarNotification,
  decideRadarNotification,
  filterNotifiableRadarEvents,
  isRadarIncidentMuted,
  type NotificationDecision,
  type NotificationSuppressionReason,
} from './notification-policy.js'
export {
  createRadarConfigFromDshProfile,
  createRadarConfigFromNpmLock,
  createRadarConfigFromPnpmLock,
  discoverDshProfiles,
  refreshRadarConfigFromConfiguredProfile,
  refreshRadarConfigFromDshProfile,
  resolveDshProfileDirectory,
  writeDshPatch,
  writeRadarConfig,
  type DshInitOptions,
  type NpmLockInitOptions,
  type PnpmLockInitOptions,
  type InitInspector,
  type WriteDshPatchOptions,
  type WriteRadarConfigOptions,
} from './init.js'
export { loadRadarState, parseRadarState, saveRadarState } from './radar-state.js'
export {
  RADAR_WEBHOOK_SCHEMA,
  buildRadarWebhookPayload,
  buildFeishuWebhookPayload,
  eventsForRadarWebhookTarget,
  isFeishuV2WebhookUrl,
  markRadarWebhookEventsDelivered,
  markRadarWebhookEventsDeliveredForRoute,
  normalizeRadarWebhookUrl,
  queueRadarWebhookEvents,
  queueRadarWebhookEventsForRoute,
  radarWebhookEndpointHash,
  resolveRadarWebhookTargets,
  sendRadarWebhook,
  toRadarWebhookEventNotice,
  undeliveredRadarWebhookEvents,
  undeliveredRadarWebhookEventsForRoute,
  type RadarWebhookEventNotice,
  type RadarWebhookPayload,
  type RadarWebhookTarget,
  type FeishuWebhookPayload,
  type SendRadarWebhookOptions,
} from './webhook.js'
export {
  evaluateRadarPolicy,
  renderRadarPolicy,
  RADAR_FAIL_THRESHOLDS,
  type RadarFailThreshold,
  type RadarPolicyMatch,
  type RadarPolicyResult,
} from './radar-policy.js'
export {
  createRadarStatus,
  createRadarNext,
  renderRadarStatus,
  renderRadarNext,
  RADAR_NEXT_SCHEMA,
  RADAR_STATUS_SCHEMA,
  type CreateRadarStatusOptions,
  type RadarMonitoringStatus,
  type RadarCoverageStatus,
  type RadarNextReport,
  type RadarStatusIncident,
  type RadarStatusTriage,
  type RadarSourceStatus,
  type RadarStatusReport,
  type RadarStatusSource,
} from './radar-status.js'
export {
  createRadarHistory,
  renderRadarHistory,
  RADAR_HISTORY_REPORT_SCHEMA,
  type CreateRadarHistoryOptions,
  type RadarHistoryReport,
} from './radar-history.js'
export { renderRadarEvent, renderRadarEvents } from './radar-render.js'
export { renderVulnerabilityPriority, vulnerabilityPriority, type VulnerabilityPriorityEvidence } from './vulnerability-priority.js'
export {
  createDoctorReport,
  renderDoctorReport,
  DOCTOR_SCHEMA,
  type DoctorCheck,
  type DoctorCheckStatus,
  type DoctorOptions,
  type DoctorOverallStatus,
  type DoctorReport,
} from './doctor.js'
export { compareSemverValues, crossesBreakingVersionBoundary, parseSemver, satisfiesSemverRange } from './semver.js'
export { scanDirectory, type ScanOptions } from './scan.js'
export { parseNpmTarball, type ParsedNpmTarball, type TarEntry, type TarOptions } from './tar.js'
export { TOOL_VERSION } from './version.js'
export {
  REPORT_SCHEMA,
  type CheckStatus,
  type Coverage,
  type CoverageVerdict,
  type DependencyEvidence,
  type DshEvidence,
  type Finding,
  type LifecycleScriptEvidence,
  type NpmEvidence,
  type NpmInstallScriptPackage,
  type NpmProvenanceEvidence,
  type ScanReport,
  type Severity,
  type Verdict,
  type VulnerabilitySummary,
} from './types.js'
export {
  ANALYSIS_TASK_SCHEMA,
  ANALYSIS_DELIVERY_SCHEMA,
  ANALYSIS_RESULT_SCHEMA,
  DEPENDENCY_GRAPH_SCHEMA,
  INVENTORY_SCHEMA,
  MAX_RADAR_HISTORY_EVENTS,
  RADAR_EVENT_SCHEMA,
  RADAR_CONFIG_SCHEMA,
  RADAR_HISTORY_SCHEMA,
  RADAR_STATE_SCHEMA,
  WEBHOOK_DELIVERY_SCHEMA,
  type AdvisoryConflict,
  type AdvisoryConflictClaim,
  type AdvisoryConflictField,
  type AdvisoryMatch,
  type AdvisorySourceName,
  type AnalysisTask,
  type AgentAnalysisResult,
  type AnalysisDelivery,
  type AnalysisDeliveryTaskReference,
  type CandidateDependencyGraphObservation,
  type CandidateDependencyGraphStatus,
  type CompatibilityDependencyCheck,
  type CompatibilityDependencyFinding,
  type CompatibilityDependencyStatus,
  type CompatibilityEvent,
  type CompatibilityRemediationCoverage,
  type CompatibilityUpgradeCandidate,
  type CompatibilityUpgradePath,
  type CompatibilityVulnerabilityRemediation,
  type CompatibilityVulnerabilityRemediationStatus,
  type CompatibilityVulnerabilityStatus,
  type CompatibilitySignal,
  type DependencyEdge,
  type DependencyHostRuntimeSource,
  type DependencyGraph,
  type DependencyKind,
  type DependencyNode,
  type DependencySource,
  type EventRoute,
  type PackageCoordinate,
  type PackageManifestSnapshot,
  type PluginInstallation,
  type ProjectInventory,
  type ProjectReference,
  type RootPeerContract,
  type RootPeerContractStatus,
  type RadarEvent,
  type RadarIncidentMute,
  type RadarIncidentTriage,
  type RadarIncidentTriageStatus,
  type RadarConfig,
  type RadarNotificationPolicy,
  type RadarSource,
  type RadarSeverity,
  type RadarState,
  type StoredAnalysisResult,
  type SourceHealthEvent,
  type SourceHealthStatus,
  type StoredSourceHealthMatch,
  type VulnerabilityAdvisory,
  type VulnerabilityEvent,
  type WebhookDeliveryState,
} from './radar-types.js'

// DSH 插件面（host bundle 以裸包名 `upstream-radar` 加载）：复用 ./dsh-plugin 的
// Cordis 入口，使 `.` 同时可作 host 插件装载，从而被 client-modules 扫描到 `dsh.client`
// （client 发现要求裸包名 loader 行；子路径 `upstream-radar/dsh` 无法归位到根包）。
export { apply, inject, name } from './dsh-plugin.js'
